# included file, define applications
# this _whole file_ is disable BUT allows generic includes without opting files in/out
# given that this file is duplicative of others, it is best it is disabled (apps can't be duplicated)
# it is also flagged as disabled (and not pinned) which means apps will be pruned)
flags = ["disabled"]
pinned = [
  "123"
]

[applications.go]
# if this application was allowed by the config, it would be disabled
# AND directories would be pruned unless pinned in the array structures
flags = ["disabled"]
[applications.go.git]
repository = "https://github.com/golang/go"
[applications.go.git.tagged]
download = "https://go.dev/dl/{{ $.Vars.Tag }}.linux-amd64.tar.gz"
filters = [
  "refs/tags/weekly",
  "refs/tags/release",
  "[0-9]rc[0-9]",
]

[applications.rg]
# an application can be disabled itself as well
# this will result in pruning of directories
flags= ["disabled"]
[applications.rg.github]
project = "BurntSushi/ripgrep"
release = { asset = "x86_64-unknown-linux-(.+?).tar.gz$" }
[applications.rg.extract]
# extraction can be skipped
skip = true
